### ISSUE TITLE
Hide specific words

### ISSUE THREAD

**Issue by forgottosave** [levi-ivel/MostUsed#1]
# Feature Request
### Problem.
Hey, I love this idea and would love to use it. Sadly it is currently quiet limited in it's functionality. With any language in general, this is a problem: There are words, which just appear very often.

Additionally, whenever other repeating content is present in files, those (obviously) overpower "normal" words. The `dataview` plugin, for example, allows to set attributes in the beginning of each file to later on formulate SQL querries based on these attributes. The downside: The top 100 used words are almost completely made up of the attribute keys, as they are constantly contained in every file, no matter the content.

### Solution?
The easiest solution would probably be to make it possible to define a **set of words** that should be **excluded** in the search (either in the settings, or even simply in a config file). This way one could filer out unwanted words.

This of course could be then fitted with many options, like pre-defined top english words, or even being able to click directly on the graph. But that would all just be "extras". A simle config file with excluded words would already be enough.

**Comment by levi-ivel** [comment]
Hello! 

You make a very valid point, I will be working on this issue as soon as possible in the form of a word blacklist. I'll update you as soon as the feature has been deployed.

**Comment by levi-ivel** [comment]
You should be able to update it now. If there are any issues or further requests, let me know.
