### ISSUE TITLE
List of Most used Words

### ISSUE THREAD

**Issue by StoicNoetic** [levi-ivel/MostUsed#3]
Is there any chance you could have an option to see the list of words? I imagine you must have created this, but I'm not a coder (nor familiar with the Obsidian internals). Would be great to be able to see a list of every word, with how many times it is used.

**Comment by levi-ivel** [comment]
Hello, 

Just so we're on the same page, you want the entire list of every single word with how many times it has been used? If so, would you like it to be able to export said list to .json or .txt?

**Comment by StoicNoetic** [comment]
Yes, that's right. Being able to export as a .txt would be great (separating word from count with a comma or tab).

**Comment by levi-ivel** [comment]
Hello, 

The plugin has been updated! Do note you first need to click the "Show most used words graph" button so that the list loads. It can be found in the plugins settings.
